- name: Build cEOS CE Dual Site with VxLAN DCI
  hosts: CEVXLANDCI
  tasks:
    - name: Generate EOS configuration Snapshots
      tags: [snapshot]
      import_role:
        name: arista.avd.eos_snapshot

    - name: Generate AVD Structured Configurations and Fabric Documentation
      tags: [generate]
      import_role:
        name: arista.avd.eos_designs
    
    - name: Generate Switch Intended Configurations and Documentation
      tags: [generate]
      import_role:
        name: arista.avd.eos_cli_config_gen
    
    - name: Deploy generated configuration to devices
      tags: [deploy]
      import_role:
        name: arista.avd.eos_config_deploy_eapi
    
    - name: Validate states on EOS devices
      tags: [verify, never]
      import_role:
        name: arista.avd.eos_validate_state
    
